services:
  alarm-api:
    image: alarm-api-simulator-alarm-api-simulator:latest
    platform: linux/amd64
    container_name: alarm-api-simulator
    environment:
      AUTH_ENABLED: "true"
    ports:
      - "8000:8000"
    # Image must already be loaded from alarm-management-api-simulator/*.tar
